export const slidesData = [
  {
    id: 1,
    badge: "⚡ SHARE YOUR VISION",
    titleNormal: "Where Brilliant Ideas Find ",
    titleGradient: "Their Community",
    description:
      "IdeaVault is a next-generation platform where innovators share, explore, and collaborate on breakthrough ideas. Post your concept, gather feedback, and watch it evolve into something extraordinary.",
    primaryBtn: "Submit Your Idea",
    secondaryBtn: "Explore Ideas",
    primaryHref: "/add-idea",
    secondaryHref: "/ideas",
    image: "/hero-incubation.png",
    glowColor: "rgba(6, 182, 212, 0.15)",
    glowColorLight: "rgba(6, 182, 212, 0.08)",
    accentFrom: "from-cyan-400",
    accentTo: "to-teal-400",
  },
  {
    id: 2,
    badge: "👥 BUILD TOGETHER",
    titleNormal: "Collaborate & Co-Create ",
    titleGradient: "With Like Minds",
    description:
      "Find creators, developers, and thinkers who share your passion. Leave comments, upvote the best concepts, and form connections that turn raw ideas into real-world impact.",
    primaryBtn: "Find Collaborators",
    secondaryBtn: "My Interactions",
    primaryHref: "/ideas",
    secondaryHref: "/my-interactions",
    image: "/hero-collaboration.png",
    glowColor: "rgba(16, 185, 129, 0.15)",
    glowColorLight: "rgba(16, 185, 129, 0.08)",
    accentFrom: "from-emerald-400",
    accentTo: "to-teal-400",
  },
  {
    id: 3,
    badge: "🔍 DISCOVER & EXPLORE",
    titleNormal: "Browse Ideas Across ",
    titleGradient: "Every Category",
    description:
      "From technology and science to art and social good — explore a curated library of innovative ideas. Filter by category, search by keyword, and discover concepts that inspire you.",
    primaryBtn: "Browse Categories",
    secondaryBtn: "Trending Ideas",
    primaryHref: "/ideas",
    secondaryHref: "/ideas",
    image: "/hero-ai-analysis.png",
    glowColor: "rgba(59, 130, 246, 0.15)",
    glowColorLight: "rgba(59, 130, 246, 0.08)",
    accentFrom: "from-blue-400",
    accentTo: "to-indigo-400",
  },
  {
    id: 4,
    badge: "🚀 YOUR IDEA DASHBOARD",
    titleNormal: "Track, Manage & Grow ",
    titleGradient: "Your Portfolio",
    description:
      "Keep all your submitted ideas in one place. Monitor engagement, read community feedback, and iterate on your concepts. Your personal idea vault is always at your fingertips.",
    primaryBtn: "My Ideas",
    secondaryBtn: "Get Started",
    primaryHref: "/my-ideas",
    secondaryHref: "/sign-up",
    image: "/hero-funding.png",
    glowColor: "rgba(139, 92, 246, 0.15)",
    glowColorLight: "rgba(139, 92, 246, 0.08)",
    accentFrom: "from-violet-400",
    accentTo: "to-purple-400",
  },
];
